<?php


namespace Tests\Ploi\Resources;


use Tests\BaseTest;
use Ploi\Resources\Site;

class AliasTest extends BaseTest
{

    /**
     * @var Site
     */
    private $site;

    public function setup(): void
    {
        parent::setup(); // TODO: Change the autogenerated stub

        $allServers = $this->getPloi()->server()->get();
        if (!empty($allServers->getJson()->data)) {
            $resource = $this->getPloi()->server($allServers->getJson()->data[0]->id);
            $serverSites = $resource->sites()->get();
            $this->site = $resource->sites($serverSites->getJson()->data[0]->id);
        }
    }

    public function testCreateAlias(): void
    {
        $response = $this->site->alias()->create(['example.com']);

        $this->assertContains('example.com', $response->getData()->aliases);
    }

    public function testListAliases(): void
    {
        $response = $this->site->alias()->get();

        $this->assertIsArray($response->getData()->aliases);
    }

    /**
     * @depends testCreateAlias
     */
    public function testDeleteAlias(): void
    {
        $response = $this->site->alias()->delete('example.com');

        $this->assertNotContains('example.com', $response->getData()->aliases);
    }
}