name: PHP Composer

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4' ]

    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run linter
        run: vendor/bin/phpstan analyse -c phpstan.neon

      #- name: Run test suite
      #  env:
      #    API_TOKEN: ${{ secrets.TEST_API_KEY }}
      #  run: composer test